### ISSUE TITLE
Research FunctionGemma as a smart-harness auxiliary

### ISSUE THREAD

**Issue by hartsock** [Gilamonster-Foundation/newt-agent#2261]
Research `google/functiongemma-270m-it` as an independent CPU auxiliary for the smart harness introduced in #2243 and implemented in draft #2260. Keep this separate from the durability, writer-ownership, and auxiliary-cache correctness repairs.

The existing comparison produced no accepted verdicts from Qwen2.5-0.5B on eight curated development fixtures. That establishes a limitation of the measured model/protocol combination, not a conclusion about other models or the task itself. Preserve those results and distinguish format validity from classification accuracy in follow-up experiments.

FunctionGemma has a specialized function-calling protocol: Google documents supplied function schemas, a developer activation instruction, and special-token call output. That differs from the current auxiliary's exact JSON-string verdict contract. See the [model card](https://huggingface.co/google/functiongemma-270m-it) and [formatting guide](https://ai.google.dev/gemma/docs/functiongemma/formatting-and-best-practices).

At review baseline `1d74bb0641a85d5df4c57bf647122064649cb6f9`, runtime model selection already exists in `SmartHarnessConfig`, including independent CPU HTTP backends. The embedded implementation supports Qwen2 only. `smart_harness_eval` still hardcodes the embedded model alias and local GGUF/tokenizer layout; its requests and replies do not support native tool schemas/calls. Merely selecting FunctionGemma does not implement its native protocol.

Follow-up work:

- [ ] Let the evaluator select reusable configurations using the existing `[smart_harness]` schema, keeping runtime/evaluator settings and admission rules aligned. Avoid another model registry or classifier implementation.
- [ ] Establish a reproducible CPU serving route for pinned FunctionGemma assets, such as a compatible llama.cpp or Ollama server independent of primary inference. Record actual placement evidence and distinguish it from an operator declaration.
- [ ] Compare compatibility with the existing JSON contract and a deliberately designed native function-call protocol for narration adjudication and context selection. Any adapter must retain the original response, validate a bounded advisory result, and preserve provenance; it must not dispatch real tools or silently repair malformed output.
- [ ] Compare candidates under recorded prompts, templates, budgets, and sampling settings. Report format failures, label accuracy, latency, and resource use separately. Use held-out cases before making quality claims; the existing eight fixtures are development examples.
- [ ] Determine whether task-specific fine-tuning is necessary and recommend an implementation route, further research, or rejection based on evidence.

Completion means reproducible configurations/commands, content-addressed reports retaining raw outputs and actual asset/configuration identities, comparative findings, and an explicit recommendation. This issue does not change the default auxiliary or relax the smart harness's experimental, opt-in status.
